# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"task9-bash" => {
        :box_name => "saaverdo/centos-7-5-8",
        :ip_addr => '192.168.11.101',
        }

  }


Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
          #box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
                  vb.memory = 1024
                  vb.cpus = 1
          end
          
          #config.vm.synced_folder ".", "/vagrant", type: "virtualbox", disabled: false

          box.vm.provision "prepare", type: "shell" do |s|
              s.inline = "yum install -y epel-release python3 mailx"
  	  end
          box.vm.provision "log_reporter", type: "shell", path: "./scripts/provision_01.sh"
      end
    end
end

