# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"nginx-lab-01" => {
        :box_name => "saaverdo/centos-7-5-8",
        :ip_addr => '192.168.11.101',
        :host_port => '8081',
        },
  :"nginx-lab-02" => {
        :box_name => "saaverdo/centos-7-5-8",
        :ip_addr => '192.168.11.102',
        :host_port => '8082',
        }
  }


Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "forwarded_port", guest: 8080, host: boxconfig[:host_port]
          #box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
                  vb.memory = 1024
                  vb.cpus = 1
          end
          
          #config.vm.synced_folder ".", "/vagrant", type: "virtualbox", disabled: false

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL
      end
    end
end

