---
# tasks file for roles/nginx
- name: NGINX | Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present

- name: Install Zabbix repo
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present
  
- name: Install zabbix-agent
  yum:
    name: zabbix-agent
    state: present

- name: Install packages
  yum:
    name: '{{ item }}'
    state: present
  loop: '{{ nginx_host_packages }}'

- name: NGINX | Install nginx package from EPEL Repo
  yum:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages

- name:
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: NGINX | Create NGINX config from template
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx-config

- name: NGINX | Create NGINX config from template
  template:
    src: agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.d/agent.conf
  notify:
    - reload zabbix-agent
  tags:
    - zabbix-config