---
# handlers file for roles/zabbix
- name: restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: reload "{{ nginx_package_name }}"
  systemd:
    name: "{{ nginx_package_name }}"
    state: reloaded
    enabled: yes

- name: restart PHP
  systemd:
    name: "{{ php_package_name }}"
    state: restarted
    enabled: yes

- name: restart_all
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - zabbix-server
    - zabbix-agent 
    - "{{ php_package_name }}"
    - "{{ nginx_package_name }}"

