---
# tasks file for roles/nginx
- name: NGINX | Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present

- name: install remi repository
  yum: name={{ item }}
  with_items:
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Install packages
  yum:
    name: '{{ item }}'
    state: present
  loop: '{{ prepare_host_packages }}'

- name: NGINX | Install nginx package from EPEL Repo
  yum:
    name: nginx
    state: present
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages

- name: NGINX | Create NGINX config from template
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx-config

- name: install PHP 7.1
  yum:
    name: "{{ item }}"
    enablerepo: remi-php71
  with_items:
    - php
    - php-mysql
    - php-mbstring
    - php-bcmath
    - php-gd
    - php-xml
    - php-ldap
  notify: 
    - reload nginx
