---
# tasks file for roles/nginx
- name: Install packages
  yum:
    name: '{{ item }}'
    state: present
  loop: '{{ prepare_host_packages }}'

- name: Install packages
  yum:
    name: centos-release-scl 
    state: present

- name:
  ansible.posix.selinux:
    policy: targeted
    state: permissive