all:
  children:
    web:
  vars:
    ansible_host: 127.0.0.1

web:  
  hosts:  
   task-13-selinux:  
      ansible_port: 2222  
      ansible_ssh_private_key_file: ./.vagrant/machines/task-13-selinux/virtualbox/private_key 
